### PR TITLE
Fix/75 result type names need readability

### LINKED ISSUE #75: integration-tests: result type names need readability
**Describe the bug**
`./src/integration-tests/results/complex.go`  

Type names `Skibbidippy`, `Bopskippity`, `Floopdidoop` are inhibiting my reading comprehension. They should at least include 
- some kind of marker of provenance, eg. `OneOf*`
- some kind of pattern indicating type relations (should I expect `Skibb` to be a child field of `Skibbidippy`?)

**To Reproduce**
```sh
> cat src/integration-tests/results/go/complex.go
```

**Expected behavior**
Funny is good, funny with structure is better!

### PR DESCRIPTION
**Pull request by meowsbits**
Resolves #75

### CODE REVIEW

**Comment by BelfordZ** [comment]
Thanks for the fix, I agree its not ideal naming originally.

That said, there seems to be a lot more than just the mentioned issue thats been fixed here. 

Could you break up these changes into seperate PRs / commits / issues?

**Comment by meowsbits** [comment]
Are we talking specifically about https://github.com/etclabscore/json-schema-to-types/pull/78/commits/275bf1ff53670e37422e724c0119a9281a283437?

**Comment by meowsbits** [comment]
Assuming so... I've just force-pushed a branch limited to the field name and respective test changes. Will open a new PR for the `/results` -> `/expecteds` change.

**Comment by BelfordZ** [comment]
@meowsbits thx ! I merged it up, LGTM!

**Pull request merged**
